# Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.

trigger: none # disable triggers based on commits.
name: $(BuildDefinitionName)_$(testRunTitle)_$(Date:yyyyMMdd)$(Rev:.r)

resources:
 repositories:
   - repository: microsoft-graph-docs
     type: github
     endpoint: microsoftgraph
     name: microsoftgraph/microsoft-graph-docs
     ref: zengin/snippets-staging # will refer to this branch as latest until master gets updated often

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:
- checkout: microsoft-graph-docs
  clean: true
  fetchDepth: 1
  persistCredentials: true

- checkout: self
  clean: true
  fetchDepth: 1

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: msgraph-sdk-raptor/**/*.csproj
    arguments: '--configuration $(buildConfiguration)'
  displayName: 'Build Projects'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '**/CsharpV1KnownFailureTests.csproj'
    arguments: '--configuration $(buildConfiguration) --logger trx --results-directory $(Agent.TempDirectory)'
    publishTestResults: false
  displayName: 'Csharp V1 Compilation Tests - Known Issues'
  continueOnError: true

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testResultsFormat: 'VSTest'
    searchFolder: '$(Agent.TempDirectory)'
    testResultsFiles: '**/*.trx'
    testRunTitle: 'V1 C# Snippet Compilation Tests - Known Issues $(testRunTitle)'
  displayName: 'Publish Test Results'